export const Auth = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
};
export const DashBoard = {
  DASHBOARD_DATA_REQUEST: "DASHBOARD_DATA_REQUEST",
  DASHBOARD_DATA_SUCCESS: "DASHBOARD_DATA_SUCCESS",
  DASHBOARD_DATA_FAILED: "DASHBOARD_DATA_FAILED",
};

export const Orders = {
  ORDERS_REQUEST: "ORDERS_REQUEST",
  ORDERS_SUCCESS: "ORDERS_SUCCESS",
  ORDERS_FAILED: "ORDERS_FAILED",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};
