export const Auth = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_REQUEST: "LOGOUT_REQUEST"
};
export const DASHBOARD_DATA_REQUEST = "DASHBOARD_DATA_REQUEST";
export const DASHBOARD_DATA_SUCCESS = "DASHBOARD_DATA_SUCCESS";
export const DASHBOARD_DATA_FAILED = "DASHBOARD_DATA_FAILED";
export const ORDERS_REQUEST = "ORDERS_REQUEST";
export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_FAILED = "ORDERS_FAILED";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
